name: Generate screenshot PNG

on:
  push:
    paths:
      - '.github/screenshot.svg'
      - '.github/**'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install rsvg-convert
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends librsvg2-bin

      - name: Convert SVG to PNG
        run: |
          set -e
          mkdir -p .github
          rsvg-convert -w 1200 -h 600 .github/screenshot.svg -o .github/screenshot.png

      - name: Commit and push PNG if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git status --porcelain | grep -q '.github/screenshot.png'; then
            git add .github/screenshot.png
            git commit -m "chore: generate screenshot.png from svg [ci skip]" || echo "no changes to commit"
            git push
          else
            echo "No changes to screenshot.png"
          fi

